import { NgModule } from '@angular/core';
import { RouterModule, Routes } from '@angular/router';

// NOTE: These components should have been generated by the Angular CLI.
// If your folder structure differs, update the import paths accordingly.
import { ReliefShellComponent } from './pages/relief-shell/relief-shell.component';
import { SchedulerComponent } from './pages/scheduler/scheduler.component';
import { BidderComponent } from './pages/bidder/bidder.component';

const routes: Routes = [
  {
    path: '',
    component: ReliefShellComponent,
    children: [
      { path: '', pathMatch: 'full', redirectTo: 'bidder' },
      { path: 'bidder', component: BidderComponent },
      { path: 'scheduler', component: SchedulerComponent }
    ]
  }
];

@NgModule({
  imports: [RouterModule.forChild(routes)],
  exports: [RouterModule]
})
export class ReliefRoutingModule {}
